### ISSUE TITLE
playtest checklist

### ISSUE THREAD

**Issue by ramyzhang** [scallionshire/Twin-Dimensions#159]
- [x] #122 
- [x] import lemon's new model and texture
- [x] fix highlighting bug with batteries
- [x] update dialoguetrigger collider in front of blue wall port
- [x] hook up overlays
- [x] exit the door
- [x] make camera a little less sensitive
- [x] make camera dodge more walls
